Continue 37 move initialize functions to constructors
NCAR/photo-decomp pull request #92
Opened 2022-06-06 19:52 UTC by K20shores

2022-06-06 21:48 UTC, K20shores commented
@mattldawson I didn't change the comments and print statements from 'initialize' to something indicating that it's a constructor. Should I?


```
(base) [kyle] NCAR/photo-decomp/src [continue-37-move-initialize-functions-to-constructors]  grep -r "initialize" *
core.F90:93:    !> Instantiate and initialize grid warehouse
core.F90:96:    !> Instantiate and initialize profile warehouse
core.F90:139:    !> instantiate and initialize spherical geometry type
core.F90:141:    !> instantiate and initialize lyman alpha, srb type
cross_section.F90:102:    character(len=*), parameter   :: Iam = 'base cross section initialize'
cross_sections/bro-br_o.F90:54:    character(len=*), parameter :: Iam = 'bro->br+o cross section initialize: '
cross_sections/hno3-oh_no2.F90:53:    character(len=*), parameter :: Iam = 'hno3 cross section initialize'
cross_sections/o2.F90:64:    character(len=*), parameter :: Iam = 'radXfer o2 cross section initialize: '
cross_sections/tint.F90:55:    character(len=*), parameter :: Iam = 'tint cross section initialize'
cross_sections/rono2.F90:53:    character(len=*), parameter :: Iam = 'rono2 cross section initialize'
delta_eddington.F90:126:    !> initialize the accumulators
grids/from_csv_file.F90:39:    character(len=*), parameter :: Iam = 'From_csv_file grid initialize: '
grids/from_config.F90:36:    character(len=*), parameter :: Iam = 'From config grid initialize: '
grids/equal_delta.F90:36:    character(len=*), parameter :: Iam = 'EqualDelta grid initialize: '
la_sr_bands.F90:75:      character(len=*), parameter :: Iam = 'la_srb initialize: '
netcdf_util.F90:43:   call ncObj%initialize(filespec, ierr=stat, action='r')
netcdf_util.F90:45:     write(*,*) Iam,'retcode from initialize = ',stat
profiles/earth_sun_distance.F90:47:    character(len=*), parameter :: Iam = 'earth sun distance initialize: '
profiles/o2.F90:46:    character(len=*), parameter :: Iam = 'From_csv_file profile initialize: '
profiles/o3.F90:47:    character(len=*), parameter :: Iam = 'O3_from_csv_file profile initialize: '
profiles/from_csv_file.F90:41:    character(len=*), parameter :: Iam = 'From_csv_file profile initialize: '
profiles/extraterrestrial_flux.F90:43:    character(len=*), parameter :: Iam = 'etflfromCsvFile Profile initialize: '
profiles/from_config.F90:40:    character(len=*), parameter :: Iam = 'From config profile initialize: '
profiles/surface_albedo.F90:40:    character(len=*), parameter :: Iam = 'From config profile initialize: '
profiles/air.F90:44:    character(len=*), parameter :: Iam = 'Air_from_csv_file profile initialize: '
profiles/solar_zenith_angle.F90:46:    character(len=*), parameter :: Iam = 'sza from time initialize: '
radiative_transfer.F90:83:    !> instantiate and initialize the radXfer cross section warehouse
radiative_transfer.F90:85:    !> instantiate and initialize the radiator warehouse
radiator.F90:68:    character(len=*), parameter   :: Iam = "Radiator initialize: "
radiators/aerosol.F90:57:    character(len=*), parameter   :: Iam = "Aerosol radiator initialize: "
spherical_geometry.F90:46:          character(len=*), parameter            :: Iam = 'sphers initialize: '
spherical_geometry.F90:150:! initialize dsdh, nid
tuvx.F90:29:  !> instatiate and initialize photolysis core object
```

2022-06-07 14:25 UTC, mattldawson requested changes
looks great! One minor change - the `src/cross_sections/o2.F90` file is not actually used. I checked with Stacy and he said it's not needed, so we can remove it.

2022-06-07 14:33 UTC, mattldawson commented
> @mattldawson I didn't change the comments and print statements from 'initialize' to something indicating that it's a constructor. Should I?

I don't think so - we have issues (e.g., #67) for removing the debugging output and apply the style. We can make any need changes then

2022-06-07 14:37 UTC, mattldawson approved these changes

2022-06-07 14:43 UTC, merged